name: Release HAProxy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Release image
        run: |
          export RELEASE=$(grep "HAPROXY_VERSION=" Dockerfile | sed 's|^.*=||g' |awk '{print $1}' | sed 's|"||g')
          docker login  -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
          docker pull million12/haproxy:stage
          docker tag million12/haproxy:stage million12/haproxy:${RELEASE}
          docker tag million12/haproxy:stage million12/haproxy:latest
          docker push million12/haproxy:${RELEASE}
          docker push million12/haproxy:latest
